### ISSUE TITLE
Add team mebers

### ISSUE THREAD

**Issue by 92943** [ShipleyCollege/ViPteam1#1]
I am unable to invite team members.

**Comment by ShipleySteve** [comment]
we can talk about this on Wednesday.

Please make sure your team has signed up.

Steve.

On 23 November 2015 at 15:59, 92943 notifications@github.com wrote:

> I am unable to invite team members.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ShipleyCollege/ViPteam1/issues/1.

## 

Steve Mullarkey
Course Coordinator - Level 3 Software Development & Games Programming (8006
Year 1)
Centre of Excellence for Business
Shipley College
Exhibition Road

Saltaire
BD18 3JW
Switchboard:     01274 327280

## 

 https://twitter.com/@Shipley_College
http://www.facebook.com/shipleycoll

## 

_THINK BEFORE YOU PRINT.....do you really need to ?_ *****\* This email and 
its attachments may be confidential and are intended solely for the use of 
the individual to whom it is addressed. Any views or opinions expressed are 
solely those of the author and do not necessarily represent those of 
Shipley College. If you are not the intended recipient of this email and 
its attachments, you must take no action based upon them, nor must you copy 
or show them to anyone. Please contact the sender if you believe you have 
received this email in error.

**Comment by 92943** [comment]
Ok, will do.
